// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  TURSO_URL: string;
  TURSO_TOKEN: string;
  VATCAN_API_TOKEN: string;
}
