// Generated by Wrangler by running `wrangler types` (hash: f7f2dc85383f9cb61d62b54834b500d3)
// Runtime types generated with workerd@1.20250604.0 2025-03-21
declare namespace Cloudflare {
  interface Env {
    CZQM_CACHE: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {
  TURSO_URL: string;
  TURSO_TOKEN: string;
  VATCAN_API_TOKEN: string;
  DISCORD_WEBHOOK_URL: string;
  DISCORD_BOT_TOKEN: string;
  DISCORD_GUILD_ID: string;
}
